---
title: 'GloBAM: A new project on Global Biomass flows of Aerial Migrants'
authors:
- "Tom Mason"
date: '2019-08-29'
summary: Monitoring, understanding and forecasting aerial migrations across the globe
image:
  caption: '_Average intensities of bird migration, inferred from weather radar data, across a) Europe over 3 weeks in autumn 2016 (from [Nilsson et al. 2019](https://doi.org/10.1111/ecog.04003)), and b) during spring across the US between 1995-2017 (from [Horton et al. 2019](https://doi.org/10.1002/fee.2029))._'
  focal_point: 'center'
output:
  blogdown::html_page:
    toc: true
    toc_depth: 1
categories: [globam, radar]
tags: [post]
---

**[GloBAM](https://globam.science)** is a new three-year research project led by the Department of Bird Migration that started during summer 2019. It is funded by [BioDivERsa](http://www.biodiversa.org), and has partners from across Belgium, Finland, the Netherlands, the UK and the USA. 

Migratory animals play key roles in shaping ecosystems through a variety of transport and trophic effects that also represent services and disservices to human infrastructure, agriculture and welfare. Their aerial and terrestrial habitats have changed dramatically over the past decades and are expected to change further, particularly due to rapid climate change, increased urbanization, wind energy installations, and habitat fragmentation. Within **GloBAM**, we aim to **monitor** the aerial migrations of animals (birds, insects and bats) using weather radar networks, **understand** global patterns in the intensity, routes and timing of aerial migrations, and to **forecast** how these migrations are likely to respond to global change.

### Monitor
We aim to tap into the potential of continental weather radar networks to monitor aerial migrations. We will use algorithms for retrieving and classifying biological targets in radar signals, which have already been designed, calibrated and validated on a small subset of radars. We hope to establish, for the first time, a two-year dataset of aerial migration from approx. 70 weather radar stations in Europe, combining this with  existing data from across the USA. 

### Understand

We hope to quantify biomass flows of aerial migrants across Europe and the USA at a variety of scales: across regions and continents, between seasons and years, and also across taxa. This will enable us to answer fundamental questions such as where and when do the highest densities of aerial migrants occur, what are the long-term changes in the abundance of aerial migrants, and how is the phenology of their movements changing? We will identify the abiotic and biotic drivers, such as weather, habitat, artificial light and wind energy installations, of the observed patterns in biomass flows of aerial migrants.

### Forecast

Finally, we hope to use our insights into from weather radar data to predict the potential consequences of future environmental change on aerial migrations at different scales and levels of complexity. Developing future scenarios for the main biotic and abiotic drivers of aerial biomass flows, we aim to determine the consequences of changes in these variables for movements and abundance of migratory populations using simulation behavioural-based models that generate predictions of migration behaviour, intensity and fate of migrant populations.


**For more information on GloBAM and for the latest news from the project, please check out the [project's website](https://globam.science)!**
